# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        MainWindow.setAccessibleName("")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(510, 520, 281, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.convertToFolder = QtWidgets.QPushButton(self.centralwidget)
        self.convertToFolder.setGeometry(QtCore.QRect(300, 450, 231, 31))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(16)
        self.convertToFolder.setFont(font)
        self.convertToFolder.setAutoFillBackground(True)
        self.convertToFolder.setObjectName("convertToFolder")
        self.ProgressFrame = QtWidgets.QFrame(self.centralwidget)
        self.ProgressFrame.setGeometry(QtCore.QRect(170, 10, 451, 161))
        self.ProgressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProgressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProgressFrame.setObjectName("ProgressFrame")
        self.conversionInProcess = QtWidgets.QLabel(self.ProgressFrame)
        self.conversionInProcess.setGeometry(QtCore.QRect(110, 70, 141, 21))
        self.conversionInProcess.setObjectName("conversionInProcess")
        self.progressBar = QtWidgets.QProgressBar(self.ProgressFrame)
        self.progressBar.setGeometry(QtCore.QRect(240, 70, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.completed = QtWidgets.QLabel(self.ProgressFrame)
        self.completed.setGeometry(QtCore.QRect(200, 110, 61, 21))
        self.completed.setObjectName("completed")

        #declare cancelButton
        self.cancelButton = QtWidgets.QPushButton(self.ProgressFrame)
        self.cancelButton.setGeometry(QtCore.QRect(300, 30, 81, 31))
        self.cancelButton.setObjectName("cancelButton")
        self.cancelButton.setVisible(False)

        #declare addPdfButton
        self.addPdfButton = QtWidgets.QPushButton(self.centralwidget)
        self.addPdfButton.clicked.connect(self.actionAddButtonPdf)

        self.addPdfButton.setGeometry(QtCore.QRect(330, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(16)
        self.addPdfButton.setFont(font)
        self.addPdfButton.setMouseTracking(False)
        self.addPdfButton.setObjectName("addPdfButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.commandLinkButton.setText(_translate("MainWindow", "https://github.com/marcos-aleph"))
        self.convertToFolder.setAccessibleName(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#386c74;\">Click here to convert to export the file to your folder :)</span></p></body></html>"))
        self.convertToFolder.setText(_translate("MainWindow", "CONVERT TO FOLDER"))
        self.conversionInProcess.setText(_translate("MainWindow", "Conversion in progress ..."))
        self.completed.setText(_translate("MainWindow", "Completed!"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.addPdfButton.setAccessibleName(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#386c74;\">Click here to add a .pdf file from your computer :)</span></p></body></html>"))
        self.addPdfButton.setText(_translate("MainWindow", "Add PDF"))
        
        
    def actionAddButtonPdf(self):
        #open directory folder logic
        object.addPdfButton.setEnable(False)
               

        while #.pdf true:
            object.actionCancelButton.setVisible(True)

    #LOGIC if .pdf = True, do...
        def actionConvertToFolder(self):
            #save in folder, logic...

        def actionCancelButton(self):
            if #.pdf true:
                #set .pdf empty
    
       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
